### ISSUE TITLE
Ca un utilizator ANABI, vreau sa pot adauga toate campurile necesare pentru o solutie

### ISSUE THREAD

**Issue by bogdanconstantinescu** [code4romania/anabi-gestiune-api#102]
In modelele din backend lipsesc cateva campuri care apar in mock-urile pentru adaugarea unei solutii pentru un bun.

Am notat pe mock-up campurile lipsa cu *?*, singura exceptie fiind "Data comunicarii catre ANAF" care exista deja (_SolutionDetails.SentToAuthoritiesDate_).

![anabi-solutie (1)](https://user-images.githubusercontent.com/301601/55022057-75525f00-5002-11e9-96d6-9265ed851ff2.png)

**Comment by Puiu** [comment]
Avem Data comunicarii catre ANAF: SolutionDetails?.SentToAuthoritiesDate
