### ISSUE TITLE
Un bun nou adaugat nu poate fi vizualizat

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/anabi-gestiune-api#146]
**Bug description**
Adaugarea unui nou bun functioneaza, dar la vizualizarea unui bun nou adaugat se primeste un status 500 Internal server error cu mesajul:

```json
{"Message":"Nullable object must have a value.","Errors":["Nullable object must have a value."]}
```

**Step to reproduce it**
- introducere bun nou
- click pe bun nou pentru vizualizare
- vizualizare bun nou

**Expected behavior**
Dupa adaugarea unui bun nou un utilizator ar tb sa poata sa vizualizeze resursa introdusa, fara erori

**Additional info**
<img width="721" alt="Screenshot 2019-07-23 at 19 50 56" src="https://user-images.githubusercontent.com/15039873/61731126-7a8ea300-ad83-11e9-801a-40ebc9a57536.png">
<img width="721" alt="Screenshot 2019-07-23 at 19 51 14" src="https://user-images.githubusercontent.com/15039873/61731136-7f535700-ad83-11e9-8203-7247776feaf9.png">

**Comment by bogdanconstantinescu** [comment]
Problema vine din acest endpoint: `http://backend.anabi-dev.code4.ro/api/assets/4/address`

**Comment by RaduCStefanescu** [comment]
Am testat, call-ul in backend intoarce un obiect address empty cand nu exista adresa adaugata pe un bun. Mai ramane de rezolvat in frontend https://github.com/code4romania/anabi-gestiune-client/issues/70
